name: php-cs-fixer

on:
    push:
        branches-ignore:
            - master
        tags:
            - v*
jobs:
    normalize:
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v2

            - name: Apply fixes
              run: |
                  composer require require hirak/prestissimo --dev
                  composer require friendsofphp/php-cs-fixer --dev
                  composer fix-style

            - uses: stefanzweifel/git-auto-commit-action@v4.0.0
              with:
                  commit_message: apply coding style fixes
